### PR TITLE
Add talairach atlas

### PR DESCRIPTION
**Pull request by miykael**
As discussed in https://github.com/miykael/atlasreader/issues/57, this PR adds FSL's Talairach atlas in MNI space.

### CODE REVIEW

**Comment by rmarkello** [comment]
Did you take the atlas directly from FSL? If I remember correctly [their license](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/Licence) is rather prohibitive in some instances, and doesn't align with the BSD-3 on the current repo. We may want to find an alternative source or add a statement about their license somewhere.

Now that I mention it, this is potentially a concern for all the atlases... Perhaps @KirstieJane might have some insight on this?

**Comment by miykael** [comment]
... \*mumble\* stupid license issue \*mumble\* ... Yes, other atlases would have the same issue. I also haven't checked yet FreeSurfer's license. Is the license thing still an issue even if we clearly cite the papers from which the atlases are coming from?

**Comment by rmarkello** [comment]
The license thing should be fine as long as we (1) clearly cite the original sources and (2) specify that the specific atlases included are under a different license than the code/rest of the repository and include a reproduction of that license...somewhere. Maybe we can include a README and LICENSE files in the `atlasreader/data` folder specifying all that info?

**Comment by KirstieJane** [comment]
Heya! Yeah - I hear you both on the annoying-different-licenses front. I agree with @rmarkello that citing and making clear that the atlases are licensed differently is the right way to go.

I think a README file in `atlasreader/data` is great, and I think you could just link to the license files from that README (if those licenses are online?) Otherwise a copy sounds good too.

Do we have any Freesurfer atlases? The licenses for those require a registration (whereas FSL just limits a bunch of commercial usage). I think @chrisfilo has a few different apps that go and check for the user's Freesurfer license before the code is run if we want to be really careful??

I did think that you could link to the user's installation of FSL and/or Freesurfer and therefore don't need to ship the atlases at all, but I've also realised that that would be a pain in the a** for me (and people like me) using a windows computer to make pretty plots!

So the alternate plan I've come up with is that when you install `atlasreader` you don't get the data automatically, but rather you're asked to reply to a commandline argument that acknowledges that you a) have a freesurfer license and b) know that the FSL atlases are distributed under a different license.

What do you think? I may have spun off the deep end and be overcomplicating everything here. But I kinda like the idea of someone having to *actively* acknowledge the different licences rather than assuming they'll go to the README file??

**Comment by rmarkello** [comment]
I was actually just playing around with running custom code during installation, so adding a little function to print something to the screen and request user response _should_ be doable! I think you're right and that's the best thing to do :slightly_smiling_face: 

As for where the atlases come from: that's a question for @miykael! I believe some do come from Freesurfer, but he'll know for sure. We could try and find alternative sources where they're licensed more freely, since these atlases tend to exist in many places... I'll work on the installation prompt, nonetheless.

**Comment by miykael** [comment]
Yes, having a `README` file in the `atlasreader/data` folder is the best approach. As @KirstieJane discussed, like this we could also directly link to the corresponding licenses.

Hmm... yes, at the moment we have mostly FSL and FreeSurfer atlases. As @KirstieJane mentioned, the advantage of providing the atlases as NIfTI files with the software makes those atlases also available to Windows users or people who don't want to install FreeSurfer or FSL. But I didn't consider the license issue at all and especially not the one with FreeSurfer's registration process. In this regard having a "pop-up" or something similar saying "be aware of the license of those atlases..." is probably the quickest approach.

We could also try to contact the corresponding authors or software developers and ask them if they approve our way (i.e. once we've established a good `README` file). What do you think?

**Comment by miykael** [comment]
As to the question of "where are the atlases coming from"? Good question! I know from where I've got most of them, but I didn't keep a nice track because at the beginning I was only using them for myself. I also know that I transformed some of them myself into NIfTI format etc.

I will go through the process again and comment everything in a step by step guide that we can then incorporate in a README file.

**Comment by rmarkello** [comment]
The `nilearn.datasets.fetch_` functions didn't return suitably standardized information about the labels of the images, if I remember correctly. Some were called 'id', others 'label', etc etc. Writing code to handle all the cases would have perhaps been more frustrating than just including the atlases ourselves. Though, now that the licensing has come up, that tradeoff might be a toss up :sweat_smile: 

As for `nilearn`'s licensing: I think they manage to get around the issue by requiring the users to call the functions and pulling directly from the source, not _shipping_ with the atlases as we need to do.

I can work on adding the installation message later tonight, but it would be great if @miykael could come up with the README file noting the origins and licenses of the atlas (and template) data!

**Comment by miykael** [comment]
I'm happy to create this README file. Now I'm just wondering if it's not the quickest to just get the atlases via `nilearn`. I will investigate it and come back to this.

**Comment by KirstieJane** [comment]
This all sounds great. I just wanted to add a little :+1: to pinging the FSL and Freesurfer developers and asking what they think. They may be totally fine with just linking to the atlas licences and then we don't have to engineer around it too much?

Alternatively, what about putting in a PR to `nilearn` to standardise their datasets?? Is that too big a task?

**Comment by miykael** [comment]
I think I will wait till PR https://github.com/miykael/atlasreader/pull/67 is merged before I contact the developers. We should also include a "**License** Please check the readme in the atlas folder to know how to cite the atlases you are using" section into the main `README.md`.

@KirstieJane and @rmarkello - the `nilearn` approach is possible. They actually provide the output in a coherent/structured way. But there are some issues with using `nilearn`:
1. Not all atlases can be downloaded with `nilearn`. For example, the Juelich or AICHA atlas. Also, `nilearn` uses AAL and not AAL2. We could of course "just" add them to the `nilearn` repo ourselves.
2. Using `nilearn`'s `fetch_` function will download more than we just need. For example, getting the 1mm cortical harvard_oxford atlas downloads a total of 30MB (as it also downloads all the other versions). All the atlases combined in `atlasreader` are only 12MB.
3. You need an internet connection, and it will download the files into a `nilearn_data` folder in your home directory. I see some permission issues on certain systems.
4. Do we really solve the license issue by just using `nilearn`? They are also only linking to the corresponding sources. So the same thing that we intend to do.

**Pull request closed without merging**
