### PR TITLE
[MAINT] add tests via github CI

### PR DESCRIPTION
**Pull request by Remi-Gau**

### CODE REVIEW

**Comment by miykael** [comment]
Looks good, will merge. Thank you very much @Remi-Gau!

**Comment by Remi-Gau** [comment]
sorry should have opened as a draft: I was also checking on my fork because some tests are failing.

**Comment by miykael** [comment]
Oh no, sorry. I was too quick. I didn't see any workflow under actions, so I thought it first needs to merge to turn and see how it goes.

**Comment by Remi-Gau** [comment]
I had made the same assumption and then checked on my fork.

will fix on my fork and open a PR

**Pull request merged**
