### PR TITLE
ENH: updates notebook to newest version

### PR DESCRIPTION
**Pull request by miykael**
Closes https://github.com/miykael/atlasreader/issues/20.
With this PR I tried to explain a bit in more details what `atlasreader` does and how it could be used. Very happy to have everyones' feedback on it.

Also, we might want to use some of this content to update the readme file?

Additionally, I think we should also have some nice example figures and tables in the readme file that nicely show how it works. Or should we upload this notebook with the cell outputs? That could also be an idea, my only concern is only that this increases the file size of this notebook from 11KB to 450KB. Hmm.. sorry that's not as shocking as I though.

### CODE REVIEW

**Comment by danjgale** [comment]
Oh wow, didn't see this when I was writing my PR.

**Comment by danjgale** [comment]
@miykael @rmarkello How should we proceed with this PR and #49 ?

**Comment by miykael** [comment]
@danjgale - shit, sorry I didn't realize that you were working on this as well. I'm so sorry, I looked at issue https://github.com/miykael/atlasreader/issues/20 and thought it's free to work on. I should know better.

**Comment by danjgale** [comment]
Ha! No worries, and likewise. I think we can manually merge both changes into one PR?

**Comment by miykael** [comment]
@danjgale - fine for me. To fully credit your work, I will first merge your PR and than integrate the changes in my PR here.

**Comment by danjgale** [comment]
Looks good to me! Thanks @miykael

**Comment by miykael** [comment]
Perfect, I will merge it than!

**Pull request merged**
